### ISSUE TITLE
Query params unparsable due to fragment manipulation

### ISSUE THREAD

**Issue by soverysour** [romariolopezc/elm-webpack-4-starter#130]
Hi,

due to how the url is manipulated (links are prepended with "#/" instead of "/", the url is updated to overwrite the path with the fragment), query parameters cannot be parsed (the "#" fragment starter eats all the remaining tokens up, and doesn't do query param parsing.

Removing in `Main` the case match on the fragment, the `"#/` to `"/"` in `Route` and the url update also in `Route` fixes this, but I'm assuming this (the manipulation of the path as a fragment) was a workaround for webpack? Since, after doing the above 3 changes, going to a path like `/something/something-deeper` triggers errors related to `/something/vendor.js` and `/something/main.js` (IIRC, it's `main.js`).

What do you think @romariolopezc ? IMO it's better to have it without the fragment magic, so as to be able to manipulate query params properly. I haven't looked further into the other webpack magic, so no clues there.

**Comment by romariolopezc** [comment]
Hello @soverysour 

The `#` in the URL is used by elm-spa-example, I just followed it. I did another PR to showcase how to use the URL parsing without `#`: https://github.com/romariolopezc/elm-webpack-4-starter/pull/44

I think is not a workaround for webpack but for some servers that doesn't allow to fallback to `index.html` (or hard to configure) from any route.

**Comment by romariolopezc** [comment]
The query params can be manipulated using: https://package.elm-lang.org/packages/elm/url/latest/Url-Parser-Query
