### ISSUE TITLE
propose changes to elm-community/elm-webpack-starter

### ISSUE THREAD

**Issue by muelli** [romariolopezc/elm-webpack-4-starter#3]
We have already way too many elm-webpack-starter projects, e.g. https://github.com/simonh1000/elm-webpack-starter, https://github.com/benansell/elm-webpack-seed, https://github.com/jiwhiz/elm-bootstrap-webpack-starter, and a handful others. Can you try to propose some of your changes to arguably *the* canonical elm-webpack repository here: https://github.com/elm-community/elm-webpack-starter?

**Comment by romariolopezc** [comment]
I agree, I'll make the PR when I have time. Thanks for this

**Comment by romariolopezc** [comment]
Issue: https://github.com/elm-community/elm-webpack-starter/issues/68
