### ISSUE TITLE
Improve webpack config by using optimization.minimizer

### ISSUE THREAD

**Issue by romariolopezc** [romariolopezc/elm-webpack-4-starter#30]
- [x] Add `optimize-css-assets-webpack-plugin` to minify css instead of `PurifyCss` minimizer
- [x] Move UglifyJS plugin to ` optimization: { minimizer: [] }`

Follow [these](https://github.com/webpack-contrib/mini-css-extract-plugin/#minimizing-for-production) to get it done

**Comment by asianfilm** [comment]
I have an Elm app that uses various semantic-ui components. The `optimize-css-assets-webpack-plugin` is not helping to strip out the unused CSS. I haven't rebuilt my project yet with `elm-webpack-4-starter` to see if it will help reduce the size of my CSS files. But perhaps consider that `optimize-css-assets-webpack-plugin` may not be the solution for all use cases. Or maybe neither solution (including `purifycss`)  fits my problem.

**Comment by romariolopezc** [comment]
Thanks for the input @asianfilm , good to know. Can you try and post your result here? Maybe it reduces your css

**Comment by romariolopezc** [comment]
@asianfilm the plugin does not strip unused CSS, that's the work of PurifyCSS.
The plugin:
> It will search for CSS assets during the Webpack build and will optimize \ minimize the CSS (by default it uses cssnano but a custom CSS processor can be specified).

Have you tried [PurgeCSS](https://github.com/FullHuman/purgecss)?
