### ISSUE TITLE
Add HMR support 

### ISSUE THREAD

**Issue by romariolopezc** [romariolopezc/elm-webpack-4-starter#40]
The current elm-hot-webpack-loader has some [caveats](https://github.com/klazuka/elm-hot-webpack-loader#caveats) that apply to this template. Will look for a better one that suits our needs

**Comment by Punie** [comment]
@romariolopezc The new version of [elm-hot](https://github.com/klazuka/elm-hot) (on which [elm-hot-webpack-loader](https://github.com/klazuka/elm-hot-webpack-loader) depends) now handles nested `Browser.Navigation.Key` in custom model.

See https://github.com/klazuka/elm-hot/issues/10

**Comment by romariolopezc** [comment]
Yes. I test it with no success. 

In fact I raised an issue in `elm-hot` repo `#13`. I'll test again when I have time, is straight forward to implement it following [this](https://github.com/klazuka/example-elm-hot-webpack).

Thanks for the heads up!
