### ISSUE TITLE
Support Terser for optimization

### ISSUE THREAD

**Issue by ynishi** [romariolopezc/elm-webpack-4-starter#50]
How about to support terser-js(https://github.com/terser-js/terser) instead of uglifyjs?

Why?

Very thanks to open starter, I'd tried to use terser-js with elm and it looks like good to work. Uglifyjs require babel with es6 and uglify-es is not maintained. terser-js is compatible with them and active. It is easy to use but sample codes are few. 

change:

* User terser-webpack-plugin instead of uglifyjs-webpack-plugin
* Use TerserPlugin instead of UglifyJsPlugin
* Use terserOptions instead of uglifyOptions

sample:
https://github.com/ynishi/peakseek-front/blob/100462b31afde1ca69663bbfeb2ba6dc8c51826c/webpack.config.js#L21-L24

**Comment by romariolopezc** [comment]
Hello @ynishi 

Let me take a look at Terser. I'm going to measure which optimizer is better (speed/final size/maintainability of the project)

Is there a specific use-case on why you would use terser? Or is just a personal preference?
